version: "3.7"
services:
  api_service:
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/algatransito?allowPublicKeyRetrieval=true    
    depends_on:
      mysqldb:
        condition: service_healthy
      
  mysqldb:
    image: "mysql:8.0"
    ports:
      - 3306:3306
    networks:
      - springapimysql-net  
    environment:
      MYSQL_DATABASE: algatransito
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p123456"]
      timeout: 20s
      retries: 10
networks:
  springapimysql-net: