version: '3.4'
services:
  db:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: algatransito
    ports:
      - "3308:3306"
    networks:
      - algatransito-network
  algatransito-docker-to-azure-with-java:
    image: algatransito-docker-to-azure-with-java
    restart: always
    build:
      context: .
      dockerfile: app/Dockerfile
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo    
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - algatransito-network  
networks:
    algatransito-network:
        driver: bridge